* cpputils-cmake.el (current version 0.0.2)
cpputils-cmake automatically enable real time syntax check (Flymake) and IntelliSense (auto-complete+auto-complete-clang) if you use [[http://www.cmake.org][CMake]].

It does all the configuration dirty job automatically for you. So you can use Flymake, auto-complete, auto-complete-clang, compile with almost no configuration.

* Dependency
cpputils-cmake is NOT dependent on any other packages. It only query useful information from files created by CMake and provide some handy Elisp functions to help you get the information easily.

To use real time C++ syntax check:
You need enable Flymake. `M-x flymake-mode` is enough. Or you can copy one line of elisp code into your .emacs:
#+BEGIN_SRC elisp
(flymake-mode)
#+END_SRC

To use IntelliSense:
You need install third party plugins `auto-complete` and `auto-complete-clang` through [[http://marmalade-repo.org/][Emacs' package manager]]. See [[http://emacswiki.org/emacs/AutoComplete][EmacsWiki]] and [[https://github.com/redguardtoo/emacs.d/blob/master/init-auto-complete.el][my configuration]] for details.

To use smart compile:
You need do nothing. Use `M-x compile` as usual.

* Install
cpputils-cmake is already uploaded to [[http://marmalade-repo.org/]]. So the best way to install it is using Emacs' package manager.

* Set up
Copy and paste below code into your .emacs:
#+BEGIN_SRC elisp
(add-hook 'c-mode-common-hook (lambda ()
  (cppcm-reload-all)
  ; fixed rinari's bug.
  (remove-hook 'find-file-hook 'rinari-launch)
  ))
#+END_SRC
* How to use it (for non-geeks)
After configuration, you can forget cpputils-cmake. Just enjoy Flymake, auto-complete, auto-complete-clang and compile. 
* Contact me
You can report at [[https://github.com/redguardtoo/cpputils-cmake]]. My email is <chenbin DOT sh AT gmail>.
* License
Copyright (C) 2012 Chen Bin

Author: Chen Bin <chenbin.sh@gmail.com> Keywords: flymake IntelliSense cmake

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see [[http://www.gnu.org/licenses/]].
