* cpputils-cmake.el (current version 0.0.4)
cpputils-cmake automatically enable real time syntax check (Flymake) and IntelliSense (auto-complete+auto-complete-clang) if you use [[http://www.cmake.org][CMake]].

It does all the configuration dirty job automatically for you. So you can use Flymake, auto-complete, auto-complete-clang, compile with almost no configuration.

* Install
cpputils-cmake is already uploaded to [[http://marmalade-repo.org/]]. So the best way to install it is using Emacs' package manager.
* Set up
Copy and paste below code into your .emacs:
#+BEGIN_SRC elisp
(add-hook 'c-mode-common-hook (lambda ()
  (cppcm-reload-all)
  ; fixed rinari's bug.
  (remove-hook 'find-file-hook 'rinari-launch)
  ))
;; OPTIONAL, avoid typing full path when starting gdb
(global-set-key (kbd "C-c C-g")
 '(lambda ()(interactive) (gud-gdb (concat "gdb --fullname " (cppcm-get-exe-path-current-buffer))))
)
#+END_SRC
* One minute step by step tutorial
** Create a hello world C++ project running one line shell script
#+BEGIN_SRC sh
mkdir -p hello/src;printf "#include <stdio.h>\nint main(void) {\nprintf(\"hello world\\n\");\nreturn 0;\n}" > hello/src/main.cpp;printf "cmake_minimum_required(VERSION 2.6)\nadd_executable(main main.cpp)" > hello/src/CMakeLists.txt
#+END_SRC

** Use cmake as usual
#+BEGIN_SRC sh
mkdir hello/build;cd hello/build;cmake ../src
#+END_SRC

If you use another directory name like "mybuild" instead of "build", you must add following line into your .emacs:
#+BEGIN_SRC elisp
(setq cppcm-build-dirname "mybuild")
#+END_SRC

** Open main.cpp with Emacs and enable flymake: `M-x flymake-mode`.
Now typing some random code and watch the real time hint on your syntax errors.

** Compile as usual
Compile the program: `M-x compile`

Note the default command line is `make -C ~/your-projects-blah-blah/hello/build`

** Start gdb
Press hot key `C-c C-g` (suppose you've copied my configuration from previous section).

Note the gud-gdb starts and the executable "~/your-projects-blah-blah/hello/build/main" is loaded automatically.

** OPTIONAL, if you've installed auto-complete and auto-complete-clang.
Use them as usual. You can see that the Intellisense/auto-complete is more precise than before.

* Contact me
You can report bugs at [[https://github.com/redguardtoo/cpputils-cmake]]. My email is <chenbin DOT sh AT gmail>.
* License
Copyright (C) 2012 Chen Bin

Author: Chen Bin <chenbin.sh@gmail.com> Keywords: flymake IntelliSense cmake

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see [[http://www.gnu.org/licenses/]].
